"""create_departments_table

Revision ID: 288f745ed472
Revises: b9234699044d
Create Date: 2026-01-02 20:35:06.805452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '288f745ed472'
down_revision = 'b9234699044d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create departments table with ltree path column
    op.execute(text("""
        CREATE TABLE departments (
            id UUID PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            description TEXT,
            parent_id UUID,
            path LTREE NOT NULL,
            depth INTEGER NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )
    """))

    # Create indexes
    op.create_index('ix_departments_parent_id', 'departments', ['parent_id'], unique=False)
    op.create_index('ix_departments_path', 'departments', ['path'], unique=False, postgresql_using='gist')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_path'), table_name='departments')
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
