export { LoginPage, RegisterPage } from "./auth";
export { DashboardPage } from "./DashboardPage";
export { TasksPage } from "./TasksPage";
export { TaskDetailPage } from "./TaskDetailPage";
export { BoardsPage } from "./BoardsPage";
export { BoardDetailPage } from "./BoardDetailPage";
export { ProjectsPage } from "./ProjectsPage";
export { ProjectDetailPage } from "./ProjectDetailPage";
export { InboxPage } from "./InboxPage";
export { FavoritesPage } from "./FavoritesPage";
export { SettingsPage } from "./SettingsPage";
export { NotFoundPage } from "./NotFoundPage";
